#!/bin/bash
#ddev-generated

## Description: Launch project creation assistant.
## Usage: aljibe-assistant
## Flags: [{"Name":"auto","Shorthand":"a", "Usage":"Non-interactive automatic installation with sane defaults (Use other options to override default values)"}, {"Name": "name", "Shorthand": "n", "type": "string", "Usage": "Project name to use. By default project name provided by DDEV is used"}, {"Name": "profile", "Shorthand": "p", "type": "string", "Usage": "Drupal profile to install (only useful if a Drupal site is being installed)"}, {"Name": "git", "Shorthand": "g", "Usage": "Do not initialize a Git repository in the project's folder (by default it is initialized)"}, {"Name": "core", "Shorthand": "c", "type": "uint", "DefValue": "11", "Usage": "Drupal core version (10 or 11) to install"}, {"Name": "install", "Shorthand": "i", "Usage": "Do not install a Drupal site after setting up the environment (by default it is installed)"}, {"Name": "theme", "Shorthand": "t", "Usage": "Install an Artisan theme an create a subtheme for the new site (by default it is not installed)"}]
## Example: "ddev aljibe-assistant"

# Include required scripts
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${SCRIPT_DIR}/includes/logo"
source "${SCRIPT_DIR}/includes/create_project"

show_logo

create_project "$@"

ddev drush status
ddev status

BOOTSTRAP_STATUS=$(ddev drush status --field=bootstrap 2>/dev/null)
echo $BOOTSTRAP_STATUS
if [ "$BOOTSTRAP_STATUS" == "Successful" ]; then
  echo -e "\e[30;48;5;2m Aljibe is now installed, you can access your site here:\e[0m"
  ddev drush uli
fi