#!/bin/bash

#ddev-generated

## Description: Launch project creation assistant.
## Usage: aljibe-assistant
## Example: "ddev aljibe-assistant"
ddev aljibe-logo
ddev aljibe-create-project
ddev aljibe-create-symlinks

echo -e "\e[30;48;5;2m Aljibe is now installed, you can access your site here:\e[0m"
ddev drush uli

echo "Removing aljibe assistant addon"
## Autoremove assistant
ddev get --remove ddev-aljibe-assistant
