#!/bin/bash
#ddev-generated

# Constants
DRUSH_ALIASES_FOLDER="./drush/sites"
BEHAT_LOCAL_FOLDER="./tests/behat/local"
DRUPAL_VERSION=d11
PROJECT_TYPE=drupal11
INSTALL_DRUPAL_10="n"
PHP_VERSION="8.3"

CYAN='\033[0;36m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
PROJECT_NAME=${DDEV_PROJECT}

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${SCRIPT_DIR}/aljibe_includes"

# Create project
# This function is called from the main script to create a new project
create_project() {
  local AUTO=$1

  echo -e "${GREEN}Launching assistant to configure the environment${NC}"
  echo ""

  configure_project
  git_setup
  ddev_start
  composer_install
  drupal_install
  behat_setup
  backstopjs_setup
  grumphp_setup
  phpunit_setup
  artefact_generator_setup
  create_subtheme
  add_custom_themes_to_aljibe
}

# Process example files
processExampleFile() {
  PATH=$1
  SUFFIX=$2
  declare -A REPLACEMENTS=$3
  cp "$PATH$SUFFIX" "$PATH"
  for KEY in "${!REPLACEMENTS[@]}"; do
    replaceInFile "$PATH" "$KEY" "${REPLACEMENTS[$KEY]}"
  done
}

# Setup several configuration files
configure_project() {
  cd ${DDEV_APPROOT} || exit

  if [ "$AUTO" == "0" ]; then
    echo -e "${CYAN}Please enter the project name (default to ${DDEV_PROJECT}):${NC}"
    read PROJECT_NAME_INPUT
  fi

  if [ "$AUTO" == "0" ]; then
    echo -e "${CYAN}By default, Drupal 11 will be installed. Do you want to install Drupal 10 instead?${NC} [y/N]"
    read INSTALL_DRUPAL_10
    if [ "$INSTALL_DRUPAL_10" == "y" ] || [ "$INSTALL_DRUPAL_10" == "Y" ]; then
      DRUPAL_VERSION=d10
      PROJECT_TYPE=drupal10
      echo "** Drupal 10 will be installed **"
    else
      echo "** Drupal 11 will be installed **"
    fi
  fi

  echo "Configuring ddev environment"
  if [ -z "$PROJECT_NAME_INPUT" ]; then
    PROJECT_NAME_INPUT=${DDEV_PROJECT}
  fi
  PROJECT_NAME=$PROJECT_NAME_INPUT

  echo "Configuring ddev project $PROJECT_NAME"
  ddev config --project-type=$PROJECT_TYPE --php-version $PHP_VERSION --project-name $PROJECT_NAME --docroot 'web' --auto

  echo "Preparing Aljibe config file"
  cp ${DDEV_APPROOT}/.ddev/aljibe.yaml.example ${DDEV_APPROOT}/.ddev/aljibe.yaml
  os_custom_sed "s/default_site\: self/default_site\: $PROJECT_NAME/g" ${DDEV_APPROOT}/.ddev/aljibe.yaml

  echo "Copying Aljibe Kickstart project files"
  ddev aljibe-kickstart --yes $DRUPAL_VERSION

  echo "Setting up Drush aliases file"
  cp "$DRUSH_ALIASES_FOLDER/sitename.site.yml.example" "$DRUSH_ALIASES_FOLDER/$PROJECT_NAME.site.yml"
  os_custom_sed "s/example/$PROJECT_NAME/g" $DRUSH_ALIASES_FOLDER/$PROJECT_NAME.site.yml

  echo "Setting up behat.yml file"
  os_custom_sed "s/example/$PROJECT_NAME/g" $BEHAT_LOCAL_FOLDER/behat.yml
}

# Setup git repo
git_setup() {
  if [ "$AUTO" == "0" ]; then
    echo -e "${CYAN}Do you want to initialize a git repository for your new project?${NC} [Y/n]"
    read  INITIALIZE_GIT
  else
    INITIALIZE_GIT="n"
  fi

  if [ "$INITIALIZE_GIT" != "n" ]; then
    ## Init with main branch
    git init -b main
    ## Create develop branch
    git checkout -b develop
  fi
}

ddev_start() {
  ddev start
}

composer_install() {
  ddev composer install
}

grumphp_setup() {
  ddev exec grumphp git:init
}

drupal_install() {
  if [ "$AUTO" == "0" ]; then
    echo -e "${CYAN}Do you want to install Drupal?${NC} [Y/n]"
    read INSTALL_DRUPAL
    if [ "$INSTALL_DRUPAL" != "n" ]; then
      AVAILABLE_PROFILES=("minimal" "standard" "demo_umami")
      echo -e "${CYAN}What install profile you want to install (minimal recommended for development)?${NC}"
      select PROFILE in "${AVAILABLE_PROFILES[@]}"; do
        echo "Installing profile $PROFILE"
        ddev drush -y si $PROFILE
        ddev drush cr
        break
      done
    fi
  else
    PROFILE="minimal"
    echo "Installing profile $PROFILE"
    ddev drush -y si $PROFILE
    ddev drush cr
  fi
}

# Create behat directories
behat_setup() {
  BEHAT_DIR="./web/sites/default/files/behat"
  BEHAT_DIR_ERRORS="$BEHAT_DIR/errors"

  if [ ! -d "$BEHAT_DIR" ]; then
    mkdir -p "$BEHAT_DIR"
    chmod 755 "$BEHAT_DIR"
  fi

  if [ ! -d "$BEHAT_DIR_ERRORS" ]; then
    mkdir -p "$BEHAT_DIR_ERRORS"
    chmod 755 "$BEHAT_DIR_ERRORS"
  fi
}

# Setup BackstopJS
# Currently empty as there are no special steps needed to setup BackstopJS. All
# required files are provided in the Aljibe Kickstart.
backstopjs_setup() {
  return;
}

artefact_generator_setup() {
  echo "Setting up artefact generator configuration file"
  cp ${DDEV_APPROOT}/vendor/metadrop/drupal-artifact-builder/.drupal-artifact-builder.yml.dist ${DDEV_APPROOT}/.drupal-artifact-builder.yml
}

phpunit_setup() {
  echo "Setting up phpunit configuration file"
  cp ${DDEV_APPROOT}/web/core/phpunit.xml.dist ${DDEV_APPROOT}/phpunit.xml

  # While https://www.drupal.org/project/drupal/issues/354725 is active we have
  # to edit PHPUnit conf file with fragile sed commands (the following lines do
  # this).

  echo "Configuring PHPUnit output directory"
  os_custom_sed "s|<parameter name=\"outputDirectory\" value=\"\"/>|<parameter name=\"outputDirectory\" value=\"${DDEV_APPROOT}/web/sites/default/files/simpletest/browser_output\"/>|g" ${DDEV_APPROOT}/phpunit.xml

  # echo "Configuring PHPUnit base URL"
  # os_custom_sed "s|<env name=\"BROWSERTEST_OUTPUT_BASE_URL\" value=\"\"/>|<env name=\"BROWSERTEST_OUTPUT_BASE_URL\" value=\"${DDEV_PRIMARY_URL}\"/>|g" ${DDEV_APPROOT}/phpunit.xml

  echo "Configuring PHPUnit base URL"
  os_custom_sed "s|<env name=\"SIMPLETEST_BASE_URL\" value=\"\"/>|<env name=\"SIMPLETEST_BASE_URL\" value=\"${DDEV_PRIMARY_URL}\"/>|g" ${DDEV_APPROOT}/phpunit.xml

  echo "Configuring PHPUnit directory paths"
  os_custom_sed "s|<directory>|<directory>web/core/|g" ${DDEV_APPROOT}/phpunit.xml

  echo "Configuring PHPUnit bootstrap file"
  os_custom_sed "s|tests/bootstrap\.php|web/core/tests/bootstrap.php|" ${DDEV_APPROOT}/phpunit.xml

  echo "Configuring PHPUnit database connection"
  os_custom_sed "s|<env name=\"SIMPLETEST_DB\" value=\"\"/>|<env name=\"SIMPLETEST_DB\" value=\"mysql://db:db@db:3306/db\"/>|g" ${DDEV_APPROOT}/phpunit.xml

  echo "Configuring tests output folder"
  os_custom_sed "s|sites/simpletest/browser_output|web/sites/simpletest/browser_output|" ${DDEV_APPROOT}/phpunit.xml

  echo "Setting up output folder"
  os_custom_sed "s/example/$PROJECT_NAME/g" $BEHAT_LOCAL_FOLDER/behat.yml

  echo "Create tests output folder"
  mkdir ${DDEV_APPROOT}/web/sites/simpletest/browser_output -p
  chmod 755 ${DDEV_APPROOT}/web/sites/simpletest/browser_output
}

# Create artisan subtheme
create_subtheme() {
  # Artisan subtheme is not optional now
  ddev drush --include="web/themes/contrib/artisan" artisan
}

# Update aljibe.yaml with custom themes so they can be compiled
add_custom_themes_to_aljibe() {
  find web/themes/custom/ -mindepth 1 -maxdepth 1 -type d -print0 | while IFS= read -r -d '' theme_path; do
    THEME=$(basename "$theme_path")
    ddev exec yq -i '.theme_paths.custom_theme = "/var/www/html/web/themes/custom/'$THEME'"' /var/www/html/.ddev/aljibe.yaml
    echo "Añadiendo $THEME a aljibe.yaml"
  done
}

os_custom_sed () {
    if [ "$DETECTED_SO" = "mac" ]; then
        # MacOS sed requires a backup extension, so we use 'bak' as a placeholder
        sed -i bak "$@"
    else
        # Linux sed supports -i without a backup extension
        sed -i "$@"
    fi
}